name: Code Scan with Bandit

on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write  # Needed to add comments to the PR
permissions:
  contents: read
  security-events: read
jobs:
  code-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 3: Install Bandit
      - name: Install Bandit
        run: pip install bandit jq

      # Step 4: Run Bandit to scan the repository
      - name: Run Bandit
        id: bandit_scan
        run: |
          bandit -r . -f json -o bandit_output.json || echo "Bandit scan completed"

      # Step 5: Analyze Bandit Results
      - name: Analyze Bandit Results
        id: analyze_results
        run: |
          critical_issues=$(jq '.results[] | select(.issue_severity=="HIGH")' bandit_output.json)
          if [ -n "$critical_issues" ]; then
            echo "action=block" >> $GITHUB_ENV
          else
            echo "action=merge" >> $GITHUB_ENV
          fi

      # Step 6: Comment on Pull Request
      - name: Comment on Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const action = process.env.action;
            const message = action === "block"
              ? "Pull request blocked: Critical vulnerabilities found."
              : "Pull request passed: No critical vulnerabilities.";
            
            if (context.payload.pull_request) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: message,
              });
            }

      # Step 7: Block or Merge Pull Request
      - name: Block or Merge Pull Request
        if: env.action == 'block'
        run: exit 1
