name: Code Scan with Bandit

on:
  pull_request:
    branches:
      - main

permissions:
  issues: write
  pull-requests: write


jobs:
  code-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment and install Bandit
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Bandit
        run: pip install bandit

      # Run Bandit to scan the repository
      - name: Run Bandit
        id: bandit_scan
        run: |
          bandit -r . -f json -o bandit_output.json || echo "Bandit scan completed"

      - name: Analyze Bandit Results
        id: analyze_results
        run: |
          critical_issues=$(jq '.results[] | select(.issue_severity=="CRITICAL")' bandit_output.json)
          if [ -n "$critical_issues" ]; then
            echo "action=block" >> $GITHUB_ENV
          else
            echo "action=merge" >> $GITHUB_ENV
          fi


      - name: Comment on Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const action = process.env.action;
            const message = action === "block" ? "Block" : "Successful";
      
            // Ensure pull request context exists
            if (context.payload.pull_request) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: message,
              });
            } else {
              console.log("No pull request context available.");
            }


      # Block or Merge Pull Request
      - name: Block or Merge Pull Request
        if: env.action == 'successful'
        run: exit 1
